dist:	trusty
sudo:	true

language: cpp

os:
    - linux

compiler:
    - gcc

env:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
    - sudo apt-get update -q
    - sudo apt-get install cmake

script:
    - mkdir
    - cd build
    - cmake ..
    - cmake --build .
    - ctest --output-on-failure
